require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FavoriteImagesController do

  # This should return the minimal set of attributes required to create a valid
  # FavoriteImage. As you add validations to FavoriteImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.attributes_for(:favorite_image) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FavoriteImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all favorite_images as @favorite_images" do
      favorite_image = FavoriteImage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:favorite_images).should eq([favorite_image])
    end
  end

  describe "GET show" do
    it "assigns the requested favorite_image as @favorite_image" do
      favorite_image = FavoriteImage.create! valid_attributes
      get :show, {:id => favorite_image.to_param}, valid_session
      assigns(:favorite_image).should eq(favorite_image)
    end
  end

  describe "GET new" do
    it "assigns a new favorite_image as @favorite_image" do
      get :new, {}, valid_session
      assigns(:favorite_image).should be_a_new(FavoriteImage)
    end
  end

  # describe "GET edit" do
  #   it "assigns the requested favorite_image as @favorite_image" do
  #     favorite_image = FavoriteImage.create! valid_attributes
  #     get :edit, {:id => favorite_image.to_param}, valid_session
  #     assigns(:favorite_image).should eq(favorite_image)
  #   end
  # end

  # describe "POST create" do
  #   describe "with valid params" do
  #     it "creates a new FavoriteImage" do
  #       expect {
  #         post :create, {:favorite_image => valid_attributes}, valid_session
  #       }.to change(FavoriteImage, :count).by(1)
  #     end

  #     it "assigns a newly created favorite_image as @favorite_image" do
  #       post :create, {:favorite_image => valid_attributes}, valid_session
  #       assigns(:favorite_image).should be_a(FavoriteImage)
  #       assigns(:favorite_image).should be_persisted
  #     end

  #     it "redirects to the created favorite_image" do
  #       post :create, {:favorite_image => valid_attributes}, valid_session
  #       response.should redirect_to(FavoriteImage.last)
  #     end
  #   end

  #   describe "with invalid params" do
  #     it "assigns a newly created but unsaved favorite_image as @favorite_image" do
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       FavoriteImage.any_instance.stub(:save).and_return(false)
  #       post :create, {:favorite_image => { "title" => "invalid value" }}, valid_session
  #       assigns(:favorite_image).should be_a_new(FavoriteImage)
  #     end

  #     it "re-renders the 'new' template" do
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       FavoriteImage.any_instance.stub(:save).and_return(false)
  #       post :create, {:favorite_image => { "title" => "invalid value" }}, valid_session
  #       response.should render_template("new")
  #     end
  #   end
  # end

  # describe "PUT update" do
  #   describe "with valid params" do
  #     it "updates the requested favorite_image" do
  #       favorite_image = FavoriteImage.create! valid_attributes
  #       puts favorite_image.inspect
  #       # Assuming there are no other favorite_images in the database, this
  #       # specifies that the FavoriteImage created on the previous line
  #       # receives the :update_attributes message with whatever params are
  #       # submitted in the request.
  #       FavoriteImage.any_instance.should_receive(:update).with(FactoryGirl.attributes_for(:favorite_image))
  #       put :update, {:id => favorite_image.to_param, :favorite_image => FactoryGirl.attributes_for(:favorite_image)}, valid_session
  #     end

  #     # it "assigns the requested favorite_image as @favorite_image" do
  #     #   favorite_image = FavoriteImage.create! valid_attributes
  #     #   put :update, {:id => favorite_image.to_param, :favorite_image => valid_attributes}, valid_session
  #     #   assigns(:favorite_image).should eq(favorite_image)
  #     # end

  #     # it "redirects to the favorite_image" do
  #     #   favorite_image = FavoriteImage.create! valid_attributes
  #     #   put :update, {:id => favorite_image.to_param, :favorite_image => valid_attributes}, valid_session
  #     #   response.should redirect_to(favorite_image)
  #     # end
  #   end

  #   # describe "with invalid params" do
  #   #   it "assigns the favorite_image as @favorite_image" do
  #   #     favorite_image = FavoriteImage.create! valid_attributes
  #   #     # Trigger the behavior that occurs when invalid params are submitted
  #   #     FavoriteImage.any_instance.stub(:save).and_return(false)
  #   #     put :update, {:id => favorite_image.to_param, :favorite_image => { "title" => "invalid value" }}, valid_session
  #   #     assigns(:favorite_image).should eq(favorite_image)
  #   #   end

  #   #   it "re-renders the 'edit' template" do
  #   #     favorite_image = FavoriteImage.create! valid_attributes
  #   #     # Trigger the behavior that occurs when invalid params are submitted
  #   #     FavoriteImage.any_instance.stub(:save).and_return(false)
  #   #     put :update, {:id => favorite_image.to_param, :favorite_image => { "title" => "invalid value" }}, valid_session
  #   #     response.should render_template("edit")
  #   #   end
  #   # end
  # end

  # describe "DELETE destroy" do
  #   it "destroys the requested favorite_image" do
  #     favorite_image = FavoriteImage.create! valid_attributes
  #     expect {
  #       delete :destroy, {:id => favorite_image.to_param}, valid_session
  #     }.to change(FavoriteImage, :count).by(-1)
  #   end

  #   it "redirects to the favorite_images list" do
  #     favorite_image = FavoriteImage.create! valid_attributes
  #     delete :destroy, {:id => favorite_image.to_param}, valid_session
  #     response.should redirect_to(favorite_images_url)
  #   end
  # end

end
